service: my-ds-store-app-back
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: sandx
  environment:
    PRODUCT_TABLE_NAME: products
    STOCK_TABLE_NAME: stocks
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PRODUCT_TABLE_NAME}"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.STOCK_TABLE_NAME}"

functions:
  getProductById:
    handler: src/functions/getProductById.getProductById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  getProducts:
    handler: src/functions/getProducts.getProducts
    events:
      - httpApi:
          path: /products
          method: get
  createProduct:
    handler: src/functions/createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post
  putMockData:
    handler: src/functions/putMockData.putMockData
    events:
      - httpApi:
          path: /create-mock
          method: put

resources:
  Resources:
    productDBDynamo:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.PRODUCT_TABLE_NAME}
    stockDBDynamo:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.STOCK_TABLE_NAME}

plugins:
  - serverless-esbuild
